version: '3.7'
services:
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    command:
      - "/usr/local/bin/docker-entrypoint.sh"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "max_connections=200"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  elasticsearch:
    image: elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  cdc:
    image: demo/cdc:latest
    environment:
      - DEBEZIUM_DATABASE_HOSTNAME=postgres
      - ELASTICSEARCH_HOST=elasticsearch
    volumes:
      - ./debezium:/Users/tsangc1/cdc/debezium
    restart: on-failure
    depends_on:
      - elasticsearch
      - postgres
    links:
      - elasticsearch
      - postgres
